services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - clients-api

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    networks:
      - clients-api
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - clients-api
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  clients-api:
